export const SET_POKEMON = 'SET_POKEMON';
export const SORT_POKEMON = 'SORT_POKEMON';
export const UPLOAD_POKEMONS = 'UPLOAD_POKEMONS';
export const SHOW_DESC = 'SHOW_DESC';
export const CLOSE_DESC = 'CLOSE_DESC';
export const SET_POKEMON_TO_COMPARE = 'SET_POKEMON_TO_COMPARE';
